export const MOCK_CITIES = [
  "Bogota",
  'Acacias',
  'Acevedo',
  'Aguachica',
  'Antioquia',
  'Arauca',
  'Armenia',
  'Atlantico',
  'Barrancabermeja',
  'Barranquilla',
  'Bello',
  'Bermudez',
  'Boyaca',
  'Bucaramanga',
  'Buenaventura',
  'Buga',
  'Cajica',
  'Calamar',
  'Caldas',
  'Candelaria',
  'Cartagena',
  'Cartago',
  'Cauca',
  'Chia',
  'Chiquinquira',
  'Chocho',
  'Columbia',
  'Corozal',
  'Cota',
  'Cumaribo',
  'Cundinamarca',
  'Dosquebradas',
  'Duitama',
  'El Colegio',
  'Engativa',
  'Envigado',
  'Espinal',
  'Florencia',
  'Floridablanca',
  'Fonseca',
  'Fundacion',
  'Fusagasuga',
  'Galapa',
  'Ginebra',
  'Giron',
  'Guarne',
  'Ibague',
  'Inirida',
  'Ipiales',
  'Itagui',
  'La Ceja',
  'La Estrella',
  'La Mesa',
  'La Union',
  'Los Patios',
  'Madrid',
  'Magdalena',
  'Manizales',
  'Miami',
  'Mitu',
  'Montenegro',
  'Mosquera',
  'Municipio de Copacabana',
  'Neiva',
  'Obando',
  'Palmira',
  'Pamplona',
  'Pasto',
  'Pereira',
  'Piedecuesta',
  'Pitalito',
  'Planadas',
  'Popayan',
  'Puerta Roja',
  'Puerto Tejada',
  'Purificacion',
  'Riohacha',
  'Rionegro',
  'Risaralda',
  'Sabana de Torres',
  'Sabaneta',
  'Sachica',
  'San Clemente',
  'San Diego',
  'San Gil',
  'San Martin',
  'Santa Marta',
  'Santa Rosa de Cabal',
  'Santa Rosa del Sur',
  'Santiago de Cali',
  'Silvania',
  'Sincelejo',
  'Soacha',
  'Sogamoso',
  'Soledad',
  'Sopo',
  'Tarapaca',
  'Tauramena',
  'Tenjo',
  'Tocancipa',
  'Tunja',
  'Turbaco',
  'Ubaque',
  'Urumita',
  'Valledupar',
  'Velez',
  'Villa del Rosario',
  'Villamaria',
  'Villavicencio',
  'Yopal',
  'Yotoco',
  'Yumbo',
];
